unlock_root: call_cryptsetup(): handle errors properly
Previously we handled all errors as incorrect password and continued
the script, but I've learnt that cryptsetup returns a differentiating
exit code.

diff --git a/scripts/tinytrd/unlock_root b/scripts/tinytrd/unlock_root
--- a/scripts/tinytrd/unlock_root
+++ b/scripts/tinytrd/unlock_root
@@ -96,8 +96,14 @@ call_cryptsetup() {
 		echo "$@" >&2;
 		[ -t 0 ] \
 			|| cat;
-	else	# Suppress errors, which are likely because of wrong password.
-		"$@" || true;
+	elif "$@";
+	then
+		return 0;
+	elif [ $? -eq 2 ];
+	then	# Wrong password, retry.
+		return 0;
+	else	# Other error, fail the script.
+		return 1;
 	fi
 }
 
